# Site settings
title: Jeroen Steenbeeke
email:
author: Jeroen Steenbeeke
description:
url: https://www.jeroensteenbeeke.nl
paginate: 5
paginate_path: "/blog/page:num/"
exclude: [ '.idea' ]

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

sass:
    sass_dir: ./_scss

